# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0f69bb5588c9f7840e1e5563a99342ed"
name = "sellers-app"
handle = "sellers-app"
application_url = "https://frequently-minolta-infection-finds.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://frequently-minolta-infection-finds.trycloudflare.com/auth/callback",
  "https://frequently-minolta-infection-finds.trycloudflare.com/auth/shopify/callback",
  "https://frequently-minolta-infection-finds.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
